_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -74.2125
  - -13.1719
  - 14
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 16
minzoom: 0
name: ''
source: "mapbox:///ediyes.984ec324"
styles: 
  - style.mss
template: ''
